name: Build LaTeX document
on:
  push:
    tags:
      - "v*.*"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          extra_fonts: |
            - ./fonts/*.otf
            - ./fonts/*.ttf
          latexmk_use_xelatex: true
        env:
          TEXINPUTS: ".:./fonts//:./config//:"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: resume.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
